# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation. e
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "RAH" ]
  pull_request:
    branches: [ "RAH" ]

permissions:
  contents: read

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Run build with Gradle Wrapper
      run: gradle build
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: build/libs
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: Package
